import {
  DEFAULT_DARK_COLORS,
  DEFAULT_LIGHT_COLORS,
  type ThemePreset,
} from '@sero-ai/ui/theme';

export const STYLEGUIDE_THEMES: ThemePreset[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Sero emerald and purple on zinc surfaces.',
    author: 'Sero',
    version: 1,
    builtin: true,
    colors: {
      light: DEFAULT_LIGHT_COLORS,
      dark: DEFAULT_DARK_COLORS,
    },
  },
  {
    id: 'diagnostic-swap',
    name: 'Diagnostic Swap',
    description: 'Makes token mistakes obvious by separating brand and status colours.',
    author: 'Sero',
    version: 1,
    builtin: true,
    colors: {
      light: {
        ...DEFAULT_LIGHT_COLORS,
        brandPrimary: '#0ea5e9',
        brandPrimaryHover: '#0284c7',
        brandPrimaryForeground: '#f8fafc',
        brandSecondary: '#f97316',
        brandSecondaryHover: '#ea580c',
        brandSecondaryForeground: '#fff7ed',
        accentPrimary: '#f97316',
        accentHover: '#ea580c',
        accentMuted: '#f973161f',
        accentCode: '#9333ea',
        statusSuccess: '#65a30d',
        statusWarning: '#ca8a04',
        statusError: '#dc2626',
        statusInfo: '#2563eb',
        borderFocus: '#0ea5e9',
        bannerPrimary: '#f97316',
      },
      dark: {
        ...DEFAULT_DARK_COLORS,
        brandPrimary: '#38bdf8',
        brandPrimaryHover: '#7dd3fc',
        brandPrimaryForeground: '#082f49',
        brandSecondary: '#fb923c',
        brandSecondaryHover: '#fdba74',
        brandSecondaryForeground: '#431407',
        accentPrimary: '#fb923c',
        accentHover: '#fdba74',
        accentMuted: '#fb923c33',
        accentCode: '#d8b4fe',
        statusSuccess: '#84cc16',
        statusWarning: '#facc15',
        statusError: '#f87171',
        statusInfo: '#60a5fa',
        borderFocus: '#38bdf8',
        bannerPrimary: '#fb923c',
      },
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'Low-colour stress test for hierarchy and contrast.',
    author: 'Sero',
    version: 1,
    builtin: true,
    colors: {
      light: {
        ...DEFAULT_LIGHT_COLORS,
        bgBase: '#fbfaf8',
        bgSurface: '#f0efeb',
        bgElevated: '#e6e3dc',
        bgOverlay: '#d8d4ca',
        bgMuted: '#c6c0b4',
        textPrimary: '#171614',
        textSecondary: '#4a4740',
        textMuted: '#767166',
        brandPrimary: '#2f3a33',
        brandPrimaryHover: '#1f2923',
        brandPrimaryForeground: '#fbfaf8',
        brandSecondary: '#6a6257',
        brandSecondaryHover: '#4f493f',
        accentPrimary: '#6a6257',
        accentHover: '#4f493f',
        accentMuted: '#6a62571f',
        accentCode: '#5f574e',
        borderFocus: '#2f3a33',
        bannerPrimary: '#6a6257',
      },
      dark: {
        ...DEFAULT_DARK_COLORS,
        bgBase: '#12110f',
        bgSurface: '#1b1916',
        bgElevated: '#24211d',
        bgOverlay: '#302c26',
        bgMuted: '#3d382f',
        textPrimary: '#f3f0ea',
        textSecondary: '#c7c0b4',
        textMuted: '#8e8679',
        brandPrimary: '#d6d0c4',
        brandPrimaryHover: '#eee8dc',
        brandPrimaryForeground: '#16130f',
        brandSecondary: '#a59b8c',
        brandSecondaryHover: '#c3b8a8',
        accentPrimary: '#a59b8c',
        accentHover: '#c3b8a8',
        accentMuted: '#a59b8c33',
        accentCode: '#d6d0c4',
        borderFocus: '#d6d0c4',
        bannerPrimary: '#a59b8c',
      },
    },
  },
];
