/**
 * LaunchPhase — creating the workspace and kicking off the agent.
 *
 * Shows a dramatic launch sequence, then a success state with
 * the option to go back and generate more ideas.
 */

import { useState, useEffect, useCallback } from 'react';
import type { AppIdea, Complexity } from '../shared/types';
import { launchIdea } from './sero-launcher';

// ── Build prompt generator ─────────────────────────────────

function buildPrompt(idea: AppIdea, complexity: Complexity): string {
  const complexityDesc = {
    low: 'Keep it simple — a single-page app with minimal features. Focus on getting something working fast.',
    medium: 'Build a solid app with multiple features, proper state management, and decent UX. Make it functional and polished.',
    high: 'Go all out — complex architecture, multiple views/pages, external APIs if needed, thorough error handling, and polished UI. Make it impressive.',
  };

  return `# SlopZilla Build Request

You are building an app that was generated by SlopZilla, the kaiju-sized AI slop idea generator. Build this with enthusiasm!

## App Concept
**Name:** ${idea.name}
**Tagline:** ${idea.tagline}
**Description:** ${idea.description}
**Slop Score:** ${idea.slopScore}/10

## Tech Stack
${idea.techStack.map((t) => `- ${t}`).join('\n')}

## Complexity Level: ${complexity.toUpperCase()}
${complexityDesc[complexity]}

## Instructions
1. Set up the project with the specified tech stack
2. Build out the core functionality described above
3. Add a fun, polished UI that matches the spirit of the app
4. Include a README.md explaining what it does and how to run it
5. Make it actually work — this should be a real, functional app

Have fun with it! This is SlopZilla-generated slop, so embrace the chaos and make something delightfully weird.`;
}

// ── Phase states ───────────────────────────────────────────

type LaunchState = 'launching' | 'success' | 'error';

interface LaunchPhaseProps {
  idea: AppIdea;
  complexity: Complexity;
  onLaunched: (workspaceId: string, sessionId: string) => void;
  onBack: () => void;
}

export function LaunchPhase({ idea, complexity, onLaunched, onBack }: LaunchPhaseProps) {
  const [state, setState] = useState<LaunchState>('launching');
  const [error, setError] = useState<string | null>(null);

  const doLaunch = useCallback(async () => {
    setState('launching');
    setError(null);

    try {
      const prompt = buildPrompt(idea, complexity);
      const result = await launchIdea(idea.name, prompt);
      setState('success');
      onLaunched(result.workspaceId, result.sessionId);
    } catch (err) {
      setState('error');
      setError(err instanceof Error ? err.message : 'Failed to launch. The kaiju stumbled.');
    }
  }, [idea, complexity, onLaunched]);

  useEffect(() => {
    doLaunch();
  }, [doLaunch]);

  if (state === 'launching') {
    return <LaunchingView idea={idea} />;
  }

  if (state === 'error') {
    return <ErrorView error={error} onRetry={doLaunch} onBack={onBack} />;
  }

  return <SuccessView idea={idea} onBack={onBack} />;
}

// ── Launching animation ────────────────────────────────────

function LaunchingView({ idea }: { idea: AppIdea }) {
  return (
    <div className="sz-animate-fade-up flex flex-col items-center justify-center px-6 py-12 relative z-10">
      {/* Godzilla firing */}
      <pre
        className="text-sm leading-tight font-mono select-none text-center mb-4"
        style={{
          color: 'var(--sz-neon)',
          filter: 'drop-shadow(0 0 16px var(--sz-neon-glow-strong))',
        }}
        aria-hidden="true"
      >
        {`   __
  /  @>=========>
 | \\__/|
 /|    |\\
/ | /\\ | \\
  || ||`}
      </pre>

      {/* Fire beam */}
      <div className="w-64 mb-8">
        <div className="sz-fire-beam" />
      </div>

      <h2
        className="sz-kaiju-text text-xl mb-2 text-center sz-animate-breathe"
        style={{ color: 'var(--sz-neon)' }}
      >
        LAUNCHING SLOP
      </h2>

      <p className="text-sm text-center mb-2" style={{ color: 'var(--sz-text)' }}>
        Building workspace for <strong style={{ color: 'var(--sz-neon)' }}>{idea.name}</strong>
      </p>

      <p className="text-xs text-center" style={{ color: 'var(--sz-text-dim)' }}>
        Creating workspace &rarr; Opening session &rarr; Unleashing the agent
      </p>

      <div className="flex gap-3 mt-6">
        <div className="sz-loading-dot" />
        <div className="sz-loading-dot" />
        <div className="sz-loading-dot" />
      </div>
    </div>
  );
}

// ── Success view ───────────────────────────────────────────

function SuccessView({ idea, onBack }: { idea: AppIdea; onBack: () => void }) {
  return (
    <div className="sz-animate-fade-up flex flex-col items-center justify-center px-6 py-12 relative z-10">
      {/* Victory Godzilla */}
      <pre
        className="text-sm leading-tight font-mono select-none text-center mb-6"
        style={{
          color: 'var(--sz-neon)',
          filter: 'drop-shadow(0 0 20px var(--sz-neon-glow-strong))',
        }}
        aria-hidden="true"
      >
        {`    __
   /  ^\\
  | \\__/|  RAWR!
  /|    |\\
 / |    | \\
   |/\\/\\|
   || ||
  _||_||_`}
      </pre>

      <h2
        className="sz-kaiju-text text-2xl mb-2 text-center"
        style={{ color: 'var(--sz-neon)' }}
      >
        SLOP DEPLOYED!
      </h2>

      <p className="text-sm text-center mb-2" style={{ color: 'var(--sz-text)' }}>
        <strong style={{ color: 'var(--sz-neon)' }}>{idea.name}</strong> has been unleashed!
      </p>

      <p className="text-xs text-center mb-8 max-w-sm" style={{ color: 'var(--sz-text-dim)' }}>
        A new workspace has been created and the Sero Agent is now building your app.
        Check the sidebar to watch the chaos unfold.
      </p>

      {/* Celebrate stats */}
      <div
        className="rounded-xl px-6 py-4 mb-8 text-center"
        style={{
          background: 'var(--sz-neon-subtle)',
          border: '1px solid var(--sz-border)',
        }}
      >
        <div className="text-xs uppercase tracking-wider mb-2" style={{ color: 'var(--sz-neon-dim)' }}>
          Mission Stats
        </div>
        <div className="flex gap-8 justify-center">
          <div>
            <div className="sz-kaiju-text text-lg" style={{ color: 'var(--sz-neon)' }}>
              {idea.slopScore}/10
            </div>
            <div className="text-xs" style={{ color: 'var(--sz-text-dim)' }}>Slop Score</div>
          </div>
          <div>
            <div className="sz-kaiju-text text-lg" style={{ color: 'var(--sz-neon)' }}>
              {idea.techStack.length}
            </div>
            <div className="text-xs" style={{ color: 'var(--sz-text-dim)' }}>Technologies</div>
          </div>
          <div>
            <div className="sz-kaiju-text text-lg" style={{ color: 'var(--sz-orange)' }}>
              100%
            </div>
            <div className="text-xs" style={{ color: 'var(--sz-text-dim)' }}>Chaos</div>
          </div>
        </div>
      </div>

      {/* Back button */}
      <button className="sz-cta" onClick={onBack}>
        <span>GENERATE MORE SLOP</span>
      </button>
    </div>
  );
}

// ── Error view ─────────────────────────────────────────────

function ErrorView({
  error,
  onRetry,
  onBack,
}: {
  error: string | null;
  onRetry: () => void;
  onBack: () => void;
}) {
  return (
    <div className="sz-animate-fade-up flex flex-col items-center justify-center px-6 py-12 relative z-10">
      <pre
        className="text-sm leading-tight font-mono select-none text-center mb-6 sz-animate-shake"
        style={{ color: 'var(--sz-red)' }}
        aria-hidden="true"
      >
        {`    __
   / x\\
  | \\__/|
  /|    |\\
 / | ~~ | \\
   || ||
  _||_||_`}
      </pre>

      <h2 className="sz-kaiju-text text-xl mb-2" style={{ color: 'var(--sz-red)' }}>
        KAIJU DOWN!
      </h2>

      <p className="text-sm text-center mb-2" style={{ color: 'var(--sz-text)' }}>
        SlopZilla stumbled while launching
      </p>

      {error && (
        <p className="text-xs text-center mb-6 max-w-sm" style={{ color: 'var(--sz-text-dim)' }}>
          {error}
        </p>
      )}

      <div className="flex gap-4">
        <button className="sz-cta" onClick={onRetry}>
          <span>Try Again</span>
        </button>
        <button
          className="text-sm px-4 py-2 rounded-full"
          style={{
            color: 'var(--sz-text-dim)',
            border: '1px solid var(--sz-border)',
          }}
          onClick={onBack}
        >
          Go Back
        </button>
      </div>
    </div>
  );
}
